### PR TITLE
[WIP] CB-1503: fixing error in python-apt install

### PR DESCRIPTION
**Pull request by ekovacs**

### CODE REVIEW

**Comment by lacikaaa** [comment]
Please squash your PR into 1 commit, and also we might need this change in rc-2.9, so we should reopen this PR based on rc-2.9

**Comment by ekovacs** [comment]
it is still a  WIP, as build progresses, but still **not** succeeds.

**Comment by lacikaaa** [comment]
ok, but there was nothing in the name of the PR or the description that this is WIP. you can always open a draft PR for WIP and switch to PR when it's ready, so you can avaid accidental merge

**Comment by ekovacs** [comment]
changeing PR name for indicating WIP. thanks!

**Comment by ekovacs** [comment]
nomatter what i try doing, python-apt fails to build from source.

@keyki @lacikaaa what do you suggest?

**Comment by horadla23** [comment]
@ekovacs have you tested this? we are installing salt in virtualenv and python-apt should installed from source because if you install it with apt-get, it will installed into system default python, not in the virtualenv python and virtualenv cannot use it. What is the issue with python-apt?

**Comment by horadla23** [comment]
could you try it with `apt-get -y build-dep ./` ?

**Comment by ekovacs** [comment]
> could you try it with `apt-get -y build-dep ./` ?

gives me
```
(salt_2017.7.5) root@cb---1905221700:/opt/python-apt# apt-get -y build-dep ./
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to find a source package for .
```

**Comment by ekovacs** [comment]
`apt-get -y build-dep python-apt` installs the dependencies, but not exactly the ones that are required for our specific, branch of: `1.1.0_beta1ubuntu0.16.04.1`

thus the next line (`python setup.py install`) will fail.

when trying to install it through pip, the builds fails:
[python-apt--build-failure-2.txt](https://github.com/hortonworks/cloudbreak-images/files/3208339/python-apt--build-failure-2.txt)

**Pull request merged**
