### PR TITLE
CB-2679 HA Postgres 9.6 support in CB's database service

### PR DESCRIPTION
**Pull request by doktoric**

### CODE REVIEW

**Comment by doktoric** [comment]
@pdarvasi can you please help with the gpg key?

**Comment by pdarvasi** [comment]
> @pdarvasi can you please help with the gpg key?

That is the same for 9.6 and 9.5 so it should be ok

**Comment by pdarvasi** [comment]
I've just tried it out and it seems that for some reason, we install postgres 9.2 for centos7.

`aws-centos7: 'postgresql-server' changed from 'absent' to '9.2.24-1.el7_5'`

**Comment by rmkellogg** [comment]
Here is the stack trace of the error: 

```
[root@transient-ami-testing-4 log]# ambari-server setup-security --security-option=encrypt-passwords --master-key=bigdata --master-key-persist=true --verbose

Using python  /usr/bin/python

Security setup options...
INFO: Loading properties from /etc/ambari-server/conf/ambari.properties
INFO: Loading properties from /etc/ambari-server/conf/ambari.properties
Please provide master key for locking the credential store:
Re-enter master key:
Do you want to persist master key. If you choose not to persist, you need to provide the Master Key while starting the ambari server as an env variable named AMBARI_SECURITY_MASTER_KEY or the start will prompt for the master key. Persist [y/n] (y)?
INFO: Loading properties from /etc/ambari-server/conf/ambari.properties
INFO: Loading properties from /etc/ambari-server/conf/ambari.properties
INFO: Loading properties from /etc/ambari-server/conf/ambari.properties
INFO: Loading properties from /etc/ambari-server/conf/ambari.properties
INFO: AMBARI_SERVER_LIB is not set, using default /usr/lib/ambari-server
INFO: Loading properties from /etc/ambari-server/conf/ambari.properties

Traceback (most recent call last):
  File "/usr/sbin/ambari-server.py", line 1060, in <module> mainBody()
  File "/usr/sbin/ambari-server.py", line 1030, in mainBody main(options, args, parser)
  File "/usr/sbin/ambari-server.py", line 980, in main    action_obj.execute()
  File "/usr/sbin/ambari-server.py", line 88, in execute self.need_restart = self.fn(*self.args, **self.kwargs)
  File "/usr/sbin/ambari-server.py", line 303, in setup_security action.execute()
  File "/usr/sbin/ambari-server.py", line 77, in execute self.fn(*self.args, **self.kwargs)
  File "/usr/lib/ambari-server/lib/ambari_server/setupSecurity.py", line 566, in setup_master_key
    SECURITY_MASTER_KEY_FILENAME, persist)
  File "/usr/lib/ambari-server/lib/ambari_server/setupSecurity.py", line 139, in save_master_key
    serverClassPath.get_full_ambari_classpath_escaped_for_shell(), master_key, key_location, persist)
  File "/usr/lib/ambari-server/lib/ambari_server/serverClassPath.py", line 94, in get_full_ambari_classpath_escaped_for_shell
    class_path = self._get_ambari_classpath()
  File "/usr/lib/ambari-server/lib/ambari_server/serverClassPath.py", line 83, in _get_ambari_classpath
    jdbc_driver_path = ambari_server.dbConfiguration.get_jdbc_driver_path(self.options, self.properties)
  File "/usr/lib/ambari-server/lib/ambari_server/dbConfiguration.py", line 621, in get_jdbc_driver_path
    dbms = factory.create(options, properties)
  File "/usr/lib/ambari-server/lib/ambari_server/dbConfiguration.py", line 511, in create
    dbmsConfig = desc.create_config(options, properties, dbId)
  File "/usr/lib/ambari-server/lib/ambari_server/dbConfiguration.py", line 81, in create_config
    return self.fn_create_config(options, properties, self.storage_key, dbId)
  File "/usr/lib/ambari-server/lib/ambari_server/dbConfiguration_linux.py", line 899, in createPGConfig
    return PGConfig(options, properties, storage_type)
  File "/usr/lib/ambari-server/lib/ambari_server/dbConfiguration_linux.py", line 436, in __init__
    PGConfig.PG_HBA_DIR = get_postgre_hba_dir(OS_FAMILY)
  File "/usr/lib/ambari-server/lib/ambari_server/utils.py", line 270, in get_postgre_hba_dir
    get_pg_hba_init_files())
OSError: [Errno 17] File exists

```

**Comment by pdarvasi** [comment]
Hi @rmkellogg ! Thanks for the report we will investigate your issue and get back asap!

**Comment by pdarvasi** [comment]
Hi @rmkellogg! Which CB version are you using? Unfortunately, this feature was only tested with the latest Cloudbreak and Cloudera Manager setup, that's why it is in the master branch.
Because of potential incompatibilities, you should start the custom image burning from the branch which [matches](https://github.com/hortonworks/cloudbreak-images#finding-the-correct-branch) your Cloudbreak version.

**Comment by rmkellogg** [comment]
We are using the master in hortonworks/ cloudbreak-images to build our image.  The last one I have had success is Sept 5, 2019 just prior to the introduction of the PostgreSQL upgrade.  Deployment is on RHEL 7.6 against HDP 3.1 (Ambari 2.7.3).  Error is "OSError: [Errno 17] File exists".  So I think the process is running twice and creating a bad symlink.  As expected our image has been customized with lots of OS hardening.  Nothing much has changed recently in that regard and has worked perfectly for 8+ months.  What I really want to know is if anyone has built and started a cluster with code in the master against HDP 3.1.  That will go along way towards understanding the problem.  Thanks.

**Comment by rmkellogg** [comment]
Tracking down CB version so I can attempt same process against specific branch as you suggested.

**Comment by rmkellogg** [comment]
Using proper rc-2.9 branch seems to help.  Appreciate your assistance.

**Pull request merged**
