### PR TITLE
CB-13906. Add sysstat (+ goaccess) packages

### PR DESCRIPTION
**Pull request by oleewere**

### CODE REVIEW

**Comment by cegganesh84** [comment]
Oliver, +1 for sysstat package. But not sure about goaccess, never seen it before, and what kind of security compliance it has.

**Comment by oleewere** [comment]
@cegganesh84 , you can generate reports like this from nginx access logs:
https://rt.goaccess.io/?20210826211303
of course I would only use that statically (so only during diagnostics) - this can be optional as the salt logs (where you need to apply '--include-salt-logs' if you want to collect that, same can be done here with '--include-nginx-report')

**Comment by cegganesh84** [comment]
Thanks for the explanation, +1 if it will **not** be exposed in a port in the customer cluster.

**Comment by oleewere** [comment]
ok, will open PR from draft once i have tested the image build

**Review by pdarvasi — APPROVED** [review]

**Pull request merged**
