### PR TITLE
CDPAM-1744: Run CCMv2 inverting proxy agent as separate user

### PR DESCRIPTION
**Pull request by pranavtharoor**
Updates permissions and ownership files required by `jumpgate-agent` to run as the `jumpgate` user.

### CODE REVIEW

**Review by zabhi — APPROVED** [review]
LGTM

**Review by lacikaaa — CHANGES_REQUESTED** [review]
could you add a state to ensure the user exists after RPM install? I'm just worried an image could be created successfully without verifying if the user is created and we depend on it only when starting the clulster with ccmv2

**Comment by lacikaaa** [comment]
@pranavtharoor LGTM but please squash your commits as we use `rebase and merge` to merge PRs and this should fit into one commit.
please ensure the commit message will have all the necessary info which is spread into multiple messages

**Comment by pranavtharoor** [comment]
@lacikaaa Thanks for the review. I'll squash them

**Review by lacikaaa — APPROVED** [review]

**Comment by pranavtharoor** [comment]
@lacikaaa If it is good to go, can you please merge this PR? I don't have access to merge it

**Review by pkedvessy — APPROVED** [review]

**Comment by pkedvessy** [comment]
@pranavtharoor Please validate your change at least for AWS. You can follow this wiki:
https://cloudera.atlassian.net/wiki/spaces/ENG/pages/1283916646/How+to+burn+and+validate+prewarmed+freeipa+image+for+testing+purposes
If the validation succeeds, we can merge your PR.

**Review by lajosrodek — APPROVED** [review]
LGTM

**Comment by pranavtharoor** [comment]
@pkedvessy I had done the validation yesterday for AWS after addressing the review comment.
I did the [image burn](http://build.eng.hortonworks.com/job/cloudbreak-image-burn-salt-v3/18047/) and the [validation](http://ci-cloudbreak.eng.hortonworks.com/view/e2e-test/job/api-e2e-imagevalidator-aws/1747/) that was triggered showed it was successful.
I [copied](http://build.eng.hortonworks.com/view/Cloudbreak/job/cloudbreak-copy-image/765/) the AMI to us-west-2 and validated it by creating an environment with it as well.

**Review by bergerdenes — CHANGES_REQUESTED** [review]
Please add `chown` for the `proxy.env` file (requirement for jumpgate agent service unit file) as well, in line 226 of user-data-helper.sh

**Comment by pranavtharoor** [comment]
@bergerdenes For the `proxy.env` file, I was thinking that the file was not directly read by jumpgate-agent and that systemd would read it and then pass the values as env variables to jumpgate-agent, so I had not chowned it. Please correct me if I am wrong in making this assumption. Or is it still a better practice to chown it to the jumpgate user? If so, I will add the chown

**Comment by bergerdenes** [comment]
@pranavtharoor your reasoning seems legit due to the fact `systemd` reads this file indeed. And `systemd` is run as `root`, I assume. I approve the PR now.

**Review by bergerdenes — APPROVED** [review]

**Comment by pranavtharoor** [comment]
Thanks for the reviews. Can this PR be merged now?
Do let me know if any more changes are needed

**Review by TheTinkerDad — APPROVED** [review]

**Pull request merged**
