### PR TITLE
Prevent overwrite of /etc/motd file

### PR DESCRIPTION
**Pull request by rmkellogg**
If the /etc/motd has content then do not overwrite with vendor motd.  Necessary to allow for inclusion of customer required motd.

### CODE REVIEW

**Comment by pdarvasi** [comment]
@rmkellogg Please rebase and resolve conflicts in order to be able to merge. Thanks!

**Comment by rmkellogg** [comment]
rebase in new branch

**Comment by pdarvasi** [comment]
If you change the PR base to hortonworks:rc-2.9 then I should be able to merge this.

**Comment by rmkellogg** [comment]
Will attempt to resolve. against correct branch this weekend.  Thanks.

**Comment by rmkellogg** [comment]
Add distinct PR for rc2.9.

**Pull request closed without merging**
